# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_ratings', models.IntegerField()),
                ('product_status', models.IntegerField()),
            ],
        ),
    ]
