# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_rating', '0003_product_table_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_User_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_ratings', models.IntegerField(default=0)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='product_table',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_table',
            name='product_status',
        ),
    ]
