# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_rating', '0004_auto_20171120_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='ratings_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product_table',
            name='ratings_count',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_table',
            name='ratings_sum',
            field=models.FloatField(default=0),
        ),
    ]
