# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_rating', '0005_auto_20171120_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_user_table',
            name='product_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
