# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_rating', '0006_auto_20171120_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_user_table',
            name='product_user',
        ),
        migrations.AddField(
            model_name='product_user_table',
            name='product_user',
            field=models.ManyToManyField(related_name='product_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
