# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_rating', '0007_auto_20171120_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='product_description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_table',
            name='product_quantity',
            field=models.IntegerField(),
        ),
    ]
