# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_rating', '0008_auto_20171121_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
