# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_rating', '0009_product_table_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_table',
            name='owner',
        ),
    ]
