# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_rating', '0011_auto_20171121_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_user_table',
            name='product_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_table',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
